
spring:
  jpa:
    database-platform: org.hibernate.dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}

eventuatelocal:
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181